=== Shivthej/Knowledge-Representation-Techniques/XML/Schema/annu.xsd
<schema xmlns="http://www.w3.org/2001/XMLSchema"
xmlns:roviodb="http://www.example.com/roviodb"
targetNamespace="http://www.example.com/roviodb" elementFormDefault="qualified" version="1.0">
 
 <element name="roviodb">
 <complexType>
  <sequence> 
   <element name="cookbook" minOccurs="1" maxOccurs="unbounded"> 
    <complexType>
	 <sequence>
	   <element name="title" type="string"/>
	   <element name="author" type="string"/>
	   <element name="recipe" type="roviodb:recipeType" minOccurs="1" maxOccurs="unbounded"/>
	 </sequence>
	 <attribute name="cookbookId" type="string"/>
     </complexType>
    </element>
   </sequence>
   <attributeGroup ref="roviodb:DbAttributes"/>
  </complexType>
 </element>
 
 <complexType name="recipeType">
  <sequence>
   <element name="rname" type="string"/>
   <element name="serves" type="positiveInteger"/>
   <element name="summary" type="string"/>
   <element name="ingredient" type="roviodb:ingType" minOccurs="1" maxOccurs="unbounded"/>
   <element name="instruction" type="roviodb:insType" minOccurs="1" maxOccurs="unbounded"/>
  </sequence>
  <attribute name="recipeId" type="string"/>
 </complexType>
 
 <complexType name="ingType">
  <sequence>
   <element name="ingredientId" type="positiveInteger"/>
   <element name="name" type="string"/>
   <element name="substitute" type="string" minOccurs="0"/>
   <element name="amount" type="positiveInteger"/>
   <element name="unit">
   <simpleType>
    <restriction base="string">
	 <enumeration value="Nos"/>
	 <enumeration value="tbsp"/>
	</restriction>
   </simpleType>
   </element>
  </sequence>
 </complexType>
 
 <complexType name="insType">
  <sequence>
   <element name="instructionId" type="positiveInteger"/>
   <element name="command" type="string"/>
  </sequence>
 </complexType>
 
 <attributeGroup name="DbAttributes">
    <attribute name="version" type="decimal" fixed="1.0" />
    <attribute name="source" type="string" />
  </attributeGroup>
 
</schema>

=== Shivthej/Knowledge-Representation-Techniques/XML/Schema/annu.xml
<?xml version="1.0" encoding="utf-8"?>
<roviodb xmlns="http://www.example.com/roviodb"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.example.com/roviodb annu.xsd">

	<cookbook cookbookId="C_21">
		<title>Angry Birds Bad Piggies Egg Recipes</title>
        <author>Bonnier Kirjat Oy</author>
		<recipe recipeId="R_11">
			<rname>Grilled Delight</rname>
			<serves>4</serves>
			<summary>A tasty grilled egg dish to be served with vegetable salad</summary>
			<ingredient>
				<ingredientId>41</ingredientId>
				<name>Egg</name>
				<substitute/>
				<amount>10</amount>
				<unit>Nos</unit>
			</ingredient>
			<ingredient>
				<ingredientId>53</ingredientId>
				<name>Cooking Spray</name>
				<substitute/>
				<amount>1</amount>
				<unit>Nos</unit>
			</ingredient>
			<instruction>
				<instructionId>101</instructionId>
				<command>Fire up an outdoor grill.</command>
			</instruction>
			<instruction>
				<instructionId>102</instructionId>
				<command>Use a muffin pan: coat all cups with cooking spray and break one egg per cup.</command>
			</instruction>
			<instruction>
				<instructionId>103</instructionId>
				<command>Place the pan on the grill and cook for 2-3 min over medium heat.</command>
			</instruction>
			<instruction>
				<instructionId>104</instructionId>
				<command>Serve with mixed vegetables/salad.</command>
			</instruction>
		</recipe>
		<recipe recipeId="R_12">
			<rname>Oven Made</rname>
			<serves>2</serves>
			<summary>Oven made egg - a delicacy with chives, peper and grated cheese</summary>
			<ingredient>
				<ingredientId>41</ingredientId>
				<name>Egg</name>
				<substitute/>
				<amount>2</amount>
				<unit>Nos</unit>
			</ingredient>
			<ingredient>
				<ingredientId>42</ingredientId>
				<name>Butter</name>
				<substitute>Olive oil</substitute>
				<amount>1</amount>
				<unit>tbsp</unit>
			</ingredient>
			<ingredient>
				<ingredientId>43</ingredientId>
				<name>Cream</name>
				<substitute/>
				<amount>2</amount>
				<unit>tbsp</unit>
			</ingredient>
			<ingredient>
				<ingredientId>44</ingredientId>
				<name>Salt</name>
				<substitute/>
				<amount>1</amount>
				<unit>tbsp</unit>
			</ingredient>
			<ingredient>
				<ingredientId>45</ingredientId>
				<name>Pepper</name>
				<substitute>Chilli</substitute>
				<amount>1</amount>
				<unit>tbsp</unit>
			</ingredient>
			<ingredient>
				<ingredientId>46</ingredientId>
				<name>Minced Chives</name>
				<substitute/>
				<amount>1</amount>
				<unit>tbsp</unit>
			</ingredient>
			<ingredient>
				<ingredientId>47</ingredientId>
				<name>Grated Cheese</name>
				<substitute/>
				<amount>1</amount>
				<unit>tbsp</unit>
			</ingredient>
			<instruction>
				<instructionId>201</instructionId>
				<command>Preheat the oven to 325 degree.</command>
			</instruction>
			<instruction>
				<instructionId>202</instructionId>
				<command>Grease inside of a ramekin with butter and pour the cream on the bottom.</command>
			</instruction>
			<instruction>
				<instructionId>203</instructionId>
				<command>Break egg on top of cream without breaking yolk.</command>
			</instruction>
			<instruction>
				<instructionId>204</instructionId>
				<command>Add salt pepper chives and grated cheese.</command>
			</instruction>
			<instruction>
				<instructionId>205</instructionId>
				<command>Bake for 12 to 15 min or until the whites have set.</command>
			</instruction>
			<instruction>
				<instructionId>206</instructionId>
				<command>Remove from oven and allow to set for 2 to 3 min before serving.</command>
			</instruction>
		</recipe>
	</cookbook>
</roviodb>
